version: '3.8'

services:
  db:
    container_name: ib_registry_db
    image: postgres:15
    environment:
      POSTGRES_DB: ib_company_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5432:5432"
    volumes:
      - ib_registry_db_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  pgadmin:
    container_name: ib_registry_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    container_name: ib_registry_app
    build: .
    depends_on:
      - db
    environment:
      - DISPLAY=${DISPLAY}
      - DB_HOST=db
      - DB_NAME=ib_company_db
      - DB_USER=admin
      - DB_PASS=secret_password
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./config:/app/config
    network_mode: host

volumes:
  ib_registry_db_data:
