version: '3.8'

services:
  ib_registry_db:
    image: postgres:15
    container_name: ib_registry_db
    environment:
      POSTGRES_DB: ib_company_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret_password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ib_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ib_company_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  ib_registry_app:
    build: .
    container_name: ib_registry_app
    depends_on:
      ib_registry_db:
        condition: service_healthy
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - ib_net
    dns:
      - 8.8.8.8
      - 8.8.4.4

  ib_registry_admin:
    image: dpage/pgadmin4
    container_name: ib_registry_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - ib_registry_db
    networks:
      - ib_net

volumes:
  db_data:

networks:
  ib_net:
    driver: bridge
